title: 'Gia Hân Group'
default_lang: vi
author:
  name: 'Tan Nguyen'
  email: tannt.itedu@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Chuyên cung cấp, tư vấn, phân phối, thi công các sản phẩm nhà thông minh Lumi.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
